[package]
name = "bitcoin_puzzle"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"] }
libsecp256k1 = "0.7"
hex = "0.4"
bs58 = "0.4"
ripemd160 = "0.9"
sha2 = "0.9"
bitcoin = { version = "0.32.2", features = ["rand"] }